INSERT INTO AutomobileParts VALUES (1, 'Brake Pad', 'Brake System', 'Mercedes', 49.99, 100);
INSERT INTO AutomobileParts VALUES (2, 'Oil Filter', 'Engine', 'Mercedes', 12.99, 150);
INSERT INTO AutomobileParts VALUES (3, 'Spark Plug', 'Ignition System', 'Mercedes', 3.99, 200);
INSERT INTO AutomobileParts VALUES (4, 'Air Filter', 'Engine', 'BMW', 14.99, 120);
INSERT INTO AutomobileParts VALUES (5, 'Battery', 'Electrical System', 'BMW', 99.99, 80);
INSERT INTO AutomobileParts VALUES (6, 'Shock Absorber', 'Suspension', 'BMW', 79.99, 90);
INSERT INTO AutomobileParts VALUES (7, 'Wiper Blades', 'Windshield', 'Audi', 15.99, 110);
INSERT INTO AutomobileParts VALUES (8, 'Oxygen Sensor', 'Exhaust System', 'Audi', 29.99, 70);
INSERT INTO AutomobileParts VALUES (9, 'Fuel Pump', 'Fuel System', 'Audi', 49.99, 60);
INSERT INTO AutomobileParts VALUES (10, 'Clutch Kit', 'Transmission', 'Porsche', 189.99, 40);
INSERT INTO AutomobileParts VALUES (11, 'Radiator', 'Cooling System', 'Porsche', 99.99, 30);
INSERT INTO AutomobileParts VALUES (12, 'Timing Belt', 'Engine', 'Porsche', 39.99, 50);
INSERT INTO AutomobileParts VALUES (13, 'Air Conditioning Compressor', 'HVAC', 'Toyota', 149.99, 30);
INSERT INTO AutomobileParts VALUES (14, 'Fuel Injector', 'Fuel System', 'Toyota', 29.99, 80);
INSERT INTO AutomobileParts VALUES (15, 'Cabin Air Filter', 'HVAC', 'Toyota', 19.99, 60);
INSERT INTO AutomobileParts VALUES (16, 'Drive Belt', 'Engine', 'Honda', 24.99, 100);
INSERT INTO AutomobileParts VALUES (17, 'Brake Rotor', 'Brake System', 'Honda', 69.99, 50);
INSERT INTO AutomobileParts VALUES (18, 'Power Steering Pump', 'Steering', 'Honda', 129.99, 40);
INSERT INTO AutomobileParts VALUES (19, 'Ignition Coil', 'Ignition System', 'Ford', 14.99, 70);
INSERT INTO AutomobileParts VALUES (20, 'Thermostat', 'Cooling System', 'Ford', 19.99, 90);
INSERT INTO AutomobileParts VALUES (21, 'Control Arm', 'Suspension', 'Ford', 49.99, 30);
INSERT INTO AutomobileParts VALUES (22, 'Starter Motor', 'Starting System', 'Chevrolet', 79.99, 20);
INSERT INTO AutomobileParts VALUES (23, 'Exhaust Manifold', 'Exhaust System', 'Chevrolet', 89.99, 15);
INSERT INTO AutomobileParts VALUES (24, 'Wheel Bearing', 'Wheel & Tire', 'Chevrolet', 29.99, 25);
INSERT INTO AutomobileParts VALUES (25, 'Transmission Fluid', 'Fluids & Lubricants', 'Nissan', 9.99, 100);
INSERT INTO AutomobileParts VALUES (26, 'Headlight Bulb', 'Lighting', 'Nissan', 5.99, 120);
INSERT INTO AutomobileParts VALUES (27, 'Alternator', 'Electrical System', 'Nissan', 99.99, 70);
INSERT INTO AutomobileParts VALUES (28, 'Brake Caliper', 'Brake System', 'Nissan', 59.99, 40);
INSERT INTO AutomobileParts VALUES (29, 'Radiator Hose', 'Cooling System', 'Kia', 12.99, 80);
INSERT INTO AutomobileParts VALUES (30, 'Wheel Hub Assembly', 'Wheel & Tire', 'Kia', 39.99, 60);
INSERT INTO AutomobileParts VALUES (31, 'O2 Sensor', 'Exhaust System', 'Kia', 29.99, 50);
INSERT INTO AutomobileParts VALUES (32, 'Air Intake Filter', 'Engine', 'Hyundai', 18.99, 70);
INSERT INTO AutomobileParts VALUES (33, 'Power Window Switch', 'Electrical System', 'Hyundai', 14.99, 90);
INSERT INTO AutomobileParts VALUES (34, 'Tie Rod End', 'Steering', 'Hyundai', 24.99, 80);
INSERT INTO AutomobileParts VALUES (35, 'Fuel Filter', 'Fuel System', 'Kia', 9.99, 100);
INSERT INTO AutomobileParts VALUES (36, 'Catalytic Converter', 'Exhaust System', 'Kia', 149.99, 30);
INSERT INTO AutomobileParts VALUES (37, 'Timing Chain', 'Engine', 'Hyundai', 34.99, 60);
INSERT INTO AutomobileParts VALUES (38, 'Steering Rack', 'Steering', 'Hyundai', 129.99, 40);
INSERT INTO AutomobileParts VALUES (39, 'Ignition Switch', 'Ignition System', 'Kia', 19.99, 50);
INSERT INTO AutomobileParts VALUES (40, 'Air Suspension Kit', 'Suspension', 'Kia', 499.99, 10);
INSERT INTO AutomobileParts VALUES (41, 'CV Joint', 'Drivetrain', 'Hyundai', 39.99, 30);
INSERT INTO AutomobileParts VALUES (42, 'Fuel Pump Relay', 'Electrical System', 'Kia', 7.99, 80);
INSERT INTO AutomobileParts VALUES (43, 'Drive Shaft', 'Drivetrain', 'Hyundai', 89.99, 20);
INSERT INTO AutomobileParts VALUES (44, 'Tail Light Assembly', 'Lighting', 'Kia', 49.99, 40);
INSERT INTO AutomobileParts VALUES (45, 'Transmission Mount', 'Transmission', 'Hyundai', 29.99, 50);
INSERT INTO AutomobileParts VALUES (46, 'Power Steering Fluid', 'Fluids & Lubricants', 'Kia', 6.99, 120);
INSERT INTO AutomobileParts VALUES (47, 'Exhaust Gasket', 'Exhaust System', 'Hyundai', 8.99, 100);
INSERT INTO AutomobileParts VALUES (48, 'Throttle Body', 'Fuel System', 'Kia', 119.99, 15);
INSERT INTO AutomobileParts VALUES (49, 'Radiator Fan', 'Cooling System', 'Hyundai', 29.99, 60);
INSERT INTO AutomobileParts VALUES (50, 'Brake Booster', 'Brake System', 'Kia', 79.99, 25);

COMMIT;