SELECT *
FROM AUTOMOBILEPARTS;

--CREATE A VIEW TO SHOW PARTS BY MERCEDESE
CREATE OR REPLACE VIEW VIEW_MER_PARTS
AS
SELECT *
FROM AUTOMOBILEPARTS
WHERE LOWER(MANUFACTURER)='mercedes';

SELECT *
FROM VIEW_MER_PARTS;
GRANT SELECT ON VIEW_MER_PARTS TO STORE_CLIENT;


